### ISSUE TITLE
Only one of mulitple style attributes is rendered

### ISSUE THREAD

**Issue by GrazingScientist** [ajnyga/embedGalley#13]
When having something like 

```
<table>
    <td id="table-cell-1234" align="center" style="background-color: royalblue">ABC</td>
</table>
```

In the HTML, only the `text-align: center` is realized in my table. The color is ignored. However, I would expect that both attributes are stacked to give the final style.

The problem is that the `add-style` template in the XSLT does not acknowledge any already present style attributes. Can this be realized?

**Comment by ajnyga** [comment]
I have not really touched the XSLT. Did you check whether https://github.com/PeerJ/jats-conversion has a better version for this?

**Comment by GrazingScientist** [comment]
Sorry! I did not realize that you did not author the XSL converter. I duplicated it (:smiling_imp:) in the corresponding repo: https://github.com/PeerJ/jats-conversion/issues/177

-> Close
