### ISSUE TITLE
Fatal error in OJS 3.1.2

### ISSUE THREAD

**Issue by GrazingScientist** [ajnyga/embedGalley#4]
In the most current version of OJS (3.1.2), articles with JATS-XML do not load anymore.

In the logs I get the error:
```
PHP Fatal error:  Uncaught  --> Smarty: 
Unable to load template 'app:plugins/generic/embedGalley/templatestemplates/articleFooter.tpl
' in 'frontend/pages/article.tpl' <-- \n  thrown in
/ojs/journal_name/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195
```

I think this may be connected to [this line ](https://github.com/ajnyga/embedGalley/blob/46996f68c4223e34ca9adc3b3866b46a0824bdd5/EmbedGalleyPlugin.inc.php#L170), but that is only a guess.

Would be awesome, if you could fix this.

**Comment by ajnyga** [comment]
Hi,

Yes the way templates are handled in 3.1.2 has changed. I have not upgraded the plugin to support 3.1.2 yet, but will do that soon.

**Comment by marlutampus** [comment]
Hi @ajnyga,

I am also getting the same error for the latest version of OJS. Hope we can have the upgraded plugin soon.

**Comment by GrazingScientist** [comment]
> Hi @ajnyga,
> 
> I am also getting the same error for the latest version of OJS. Hope we can have the upgraded plugin soon.

Because we are all unable to code PHP. 😁

**Comment by ajnyga** [comment]
Hi,

Took longer than I expected, but there is now a release for 3.1.2!
