### ISSUE TITLE
Call stylesheet with path not URL

### ISSUE THREAD

**Issue by GrazingScientist** [ajnyga/embedGalley#7]
I would recommend to call the stylesheet not with the server URL but with the path on the server. This avoids the plugin not working in journals that are behind some kind of firewall...

In function ```_generateHTML```:

```
$path = Core::getBaseDir() . DIRECTORY_SEPARATOR . $this->getPluginPath() . DIRECTORY_SEPARATOR . 'xsl' . DIRECTORY_SEPARATOR . $citation_style . ".xsl";
```

This solution was already proposed in #2, but unfortunately not included in the software yet.

**Comment by ajnyga** [comment]
Thanks, this will be in the 3.2 release.

**Comment by GrazingScientist** [comment]
Seems like you are spring-cleaning! 👍
