### ISSUE TITLE
Fix whitespace problem with binaries (images)

### ISSUE THREAD

**Issue by asmecher** [ajnyga/embedGalley#8]
The OJS 3.1.2 release https://github.com/ajnyga/embedGalley/releases/download/1.0.0.2/embedGalley.tar.gz appears to serve up whitespace at the start of images. Reported here:

https://forum.pkp.sfu.ca/t/do-images-get-corrupted-in-ojs-3-1-2-4/59058

This appears to come from whitespace after closing `?>` PHP end tags, e.g. in `EmbedGalleyPlugin.inc.php`.

I propose removing the PHP end tags.

**Comment by asmecher** [comment]
(PR: https://github.com/ajnyga/embedGalley/pull/9)

**Comment by ajnyga** [comment]
thanks alec
